# Generated by Django 3.2.5 on 2021-07-28 08:46

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('pybasic', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Topics',
            new_name='Topic',
        ),
    ]
