# Generated by Django 3.2.5 on 2021-08-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybasic', '0004_tags_tagtopics'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='tags',
            field=models.ManyToManyField(through='pybasic.TagTopics', to='pybasic.Tags'),
        ),
    ]
