# Generated by Django 3.2.5 on 2021-08-17 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybasic', '0007_questions_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='json_field',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
