# Generated by Django 3.2.5 on 2021-08-17 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybasic', '0008_questions_json_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='json_field',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
